theme: jekyll-theme-cayman
files_root: https://github.com/vrw-GH/vrw-GH/raw/main/
file_1: resume/victor-wright_cv.pdf
file_2: certificates/Victor-Wright_WBS-RecommendationLetter.pdf
file_3: certificates/Victor-Wright_WBS-FullStackWeb&AppDev.pdf
file_4: certificates/Victor-Wright_UOM-FrontEndWebDevelopment.pdf
file_5: certificates/Victor-Wright_JFA-EmpCertificate.pdf
